In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv')
df

,Sno,State / Union Territory,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,1,Uttar Pradesh,199812341,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
1,2,Maharashtra,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
2,3,Bihar,104099452,92341436,11758016,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
3,4,West Bengal,91276115,62183113,29093002,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
4,5,Madhya Pradesh,72626809,52557404,20069405,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
5,6,Tamil Nadu,72147030,37229590,34917440,"130,058 km2 (50,216 sq mi)","555/km2 (1,440/sq mi)",996
6,7,Rajasthan,68548437,51500352,17048085,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
7,8,Karnataka,61095297,37469335,23625962,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),973
8,9,Gujarat,60439692,34694609,25745083,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
9,10,Andhra Pradesh,49577103,34966693,14610410,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993
10,11,Odisha,41974218,34970562,7003656,"155,707 km2 (60,119 sq mi)",269/km2 (700/sq mi),979
11,12,Telengana,35003674,21395009,13608665,"112,077 km2 (43,273 sq mi)",312/km2 (810/sq mi),988
12,13,Kerala,33406061,17471135,15934926,"38,863 km2 (15,005 sq mi)","859/km2 (2,220/sq mi)",1084
13,14,Jharkhand,32988134,25055073,7933061,"79,714 km2 (30,778 sq mi)","414/km2 (1,070/sq mi)",948
14,15,Assam,31205576,26807034,4398542,"78,438 km2 (30,285 sq mi)","397/km2 (1,030/sq mi)",954
15,16,Punjab,27743338,17344192,10399146,"50,362 km2 (19,445 sq mi)","550/km2 (1,400/sq mi)",895
16,17,Chhattisgarh,25545198,19607961,5937237,"135,191 km2 (52,198 sq mi)",189/km2 (490/sq mi),991
17,18,Haryana,25351462,16509359,8842103,"44,212 km2 (17,070 sq mi)","573/km2 (1,480/sq mi)",879
18,19,Uttarakhand,10086292,7036954,3049338,"53,483 km2 (20,650 sq mi)",189/km2 (490/sq mi),963
19,20,Himachal Pradesh,6864602,6176050,688552,"55,673 km2 (21,495 sq mi)",123/km2 (320/sq mi),972
20,21,Tripura,3673917,2712464,961453,"10,486 km2 (4,049 sq mi)",350/km2 (910/sq mi),960
21,22,Meghalaya,2966889,2371439,595450,"22,429 km2 (8,660 sq mi)",132/km2 (340/sq mi),989
22,23,Manipur,2570390,1793875,776515,"22,327 km2 (8,621 sq mi)",122/km2 (320/sq mi),992
23,24,Nagaland,1978502,1407536,570966,"16,579 km2 (6,401 sq mi)",119/km2 (310/sq mi),931
24,25,Goa,1458545,551731,906814,"3,702 km2 (1,429 sq mi)","394/km2 (1,020/sq mi)",973
25,26,Arunachal Pradesh,1383727,1066358,317369,"83,743 km2 (32,333 sq mi)",17/km2 (44/sq mi),938
26,27,Mizoram,1097206,525435,571771,"21,081 km2 (8,139 sq mi)",52/km2 (130/sq mi),976
27,28,Sikkim,610577,456999,153578,"7,096 km2 (2,740 sq mi)",86/km2 (220/sq mi),890
28,29,Delhi,16787941,419042,16368899,"1,484 km2 (573 sq mi)","11,297/km2 (29,260/sq mi)",868
29,30,Jammu and Kashmir,12267032,9064220,3202812,"125,535 km2 (48,469 sq mi)",98/km2 (250/sq mi),890
30,31,Puducherry,1247953,395200,852753,479 km2 (185 sq mi),"2,598/km2 (6,730/sq mi)",1037
31,32,Chandigarh,1055450,28991,1026459,114 km2 (44 sq mi),"9,252/km2 (23,960/sq mi)",818
32,33,Dadra and Nagar Haveli and Daman and Diu,585764,243510,342254,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
33,34,Andaman and Nicobar Islands,380581,237093,143488,"8,249 km2 (3,185 sq mi)",46/km2 (120/sq mi),876
34,35,Ladakh,274000,43840,230160,"96,701 km2 (37,336 sq mi)",2.8/km2 (7.3/sq mi),853
35,36,Lakshadweep,64473,14141,50332,32 km2 (12 sq mi),"2,013/km2 (5,210/sq mi)",946

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
#To Know the all columns name
df.columns

Index(['Sno', 'State / Union Territory', 'Population', 'Rural population',
       'Urban population', 'Area', 'Density', 'Gender Ratio'],
      dtype='object')

In [5]:
#Parameters to write the files.
#(1)nrows:
#To display the number of rows we want.
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv',nrows=1)
df

,Sno,State / Union Territory,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,1,Uttar Pradesh,199812341,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912

In [6]:
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv',nrows=3)
df

,Sno,State / Union Territory,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,1,Uttar Pradesh,199812341,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
1,2,Maharashtra,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
2,3,Bihar,104099452,92341436,11758016,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918

In [7]:
#To display column also.
#(2)usecols:
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv',usecols=[0])
df

    Sno
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
10   11
11   12
12   13
13   14
14   15
15   16
16   17
17   18
18   19
19   20
20   21
21   22
22   23
23   24
24   25
25   26
26   27
27   28
28   29
29   30
30   31
31   32
32   33
33   34
34   35
35   36

In [8]:
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv',usecols=[2,4,7])
df

    Population  Urban population  Gender Ratio
0    199812341          44495063           912
1    112374333          50818259           929
2    104099452          11758016           918
3     91276115          29093002           953
4     72626809          20069405           931
5     72147030          34917440           996
6     68548437          17048085           928
7     61095297          23625962           973
8     60439692          25745083           919
9     49577103          14610410           993
10    41974218           7003656           979
11    35003674          13608665           988
12    33406061          15934926          1084
13    32988134           7933061           948
14    31205576           4398542           954
15    27743338          10399146           895
16    25545198           5937237           991
17    25351462           8842103           879
18    10086292           3049338           963
19     6864602            688552           972
20     3673917            961453           960
21     2966889            595450           989
22     2570390            776515           992
23     1978502            570966           931
24     1458545            906814           973
25     1383727            317369           938
26     1097206            571771           976
27      610577            153578           890
28    16787941          16368899           868
29    12267032           3202812           890
30     1247953            852753          1037
31     1055450           1026459           818
32      585764            342254           711
33      380581            143488           876
34      274000            230160           853
35       64473             50332           946

In [9]:
#Removing new hidings
#(3)skiprows
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv',skiprows=[1])
df

,Sno,State / Union Territory,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,2,Maharashtra,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
1,3,Bihar,104099452,92341436,11758016,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
2,4,West Bengal,91276115,62183113,29093002,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
3,5,Madhya Pradesh,72626809,52557404,20069405,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
4,6,Tamil Nadu,72147030,37229590,34917440,"130,058 km2 (50,216 sq mi)","555/km2 (1,440/sq mi)",996
5,7,Rajasthan,68548437,51500352,17048085,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
6,8,Karnataka,61095297,37469335,23625962,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),973
7,9,Gujarat,60439692,34694609,25745083,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
8,10,Andhra Pradesh,49577103,34966693,14610410,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993
9,11,Odisha,41974218,34970562,7003656,"155,707 km2 (60,119 sq mi)",269/km2 (700/sq mi),979
10,12,Telengana,35003674,21395009,13608665,"112,077 km2 (43,273 sq mi)",312/km2 (810/sq mi),988
11,13,Kerala,33406061,17471135,15934926,"38,863 km2 (15,005 sq mi)","859/km2 (2,220/sq mi)",1084
12,14,Jharkhand,32988134,25055073,7933061,"79,714 km2 (30,778 sq mi)","414/km2 (1,070/sq mi)",948
13,15,Assam,31205576,26807034,4398542,"78,438 km2 (30,285 sq mi)","397/km2 (1,030/sq mi)",954
14,16,Punjab,27743338,17344192,10399146,"50,362 km2 (19,445 sq mi)","550/km2 (1,400/sq mi)",895
15,17,Chhattisgarh,25545198,19607961,5937237,"135,191 km2 (52,198 sq mi)",189/km2 (490/sq mi),991
16,18,Haryana,25351462,16509359,8842103,"44,212 km2 (17,070 sq mi)","573/km2 (1,480/sq mi)",879
17,19,Uttarakhand,10086292,7036954,3049338,"53,483 km2 (20,650 sq mi)",189/km2 (490/sq mi),963
18,20,Himachal Pradesh,6864602,6176050,688552,"55,673 km2 (21,495 sq mi)",123/km2 (320/sq mi),972
19,21,Tripura,3673917,2712464,961453,"10,486 km2 (4,049 sq mi)",350/km2 (910/sq mi),960
20,22,Meghalaya,2966889,2371439,595450,"22,429 km2 (8,660 sq mi)",132/km2 (340/sq mi),989
21,23,Manipur,2570390,1793875,776515,"22,327 km2 (8,621 sq mi)",122/km2 (320/sq mi),992
22,24,Nagaland,1978502,1407536,570966,"16,579 km2 (6,401 sq mi)",119/km2 (310/sq mi),931
23,25,Goa,1458545,551731,906814,"3,702 km2 (1,429 sq mi)","394/km2 (1,020/sq mi)",973
24,26,Arunachal Pradesh,1383727,1066358,317369,"83,743 km2 (32,333 sq mi)",17/km2 (44/sq mi),938
25,27,Mizoram,1097206,525435,571771,"21,081 km2 (8,139 sq mi)",52/km2 (130/sq mi),976
26,28,Sikkim,610577,456999,153578,"7,096 km2 (2,740 sq mi)",86/km2 (220/sq mi),890
27,29,Delhi,16787941,419042,16368899,"1,484 km2 (573 sq mi)","11,297/km2 (29,260/sq mi)",868
28,30,Jammu and Kashmir,12267032,9064220,3202812,"125,535 km2 (48,469 sq mi)",98/km2 (250/sq mi),890
29,31,Puducherry,1247953,395200,852753,479 km2 (185 sq mi),"2,598/km2 (6,730/sq mi)",1037
30,32,Chandigarh,1055450,28991,1026459,114 km2 (44 sq mi),"9,252/km2 (23,960/sq mi)",818
31,33,Dadra and Nagar Haveli and Daman and Diu,585764,243510,342254,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
32,34,Andaman and Nicobar Islands,380581,237093,143488,"8,249 km2 (3,185 sq mi)",46/km2 (120/sq mi),876
33,35,Ladakh,274000,43840,230160,"96,701 km2 (37,336 sq mi)",2.8/km2 (7.3/sq mi),853
34,36,Lakshadweep,64473,14141,50332,32 km2 (12 sq mi),"2,013/km2 (5,210/sq mi)",946

In [10]:
#To remove multiple rows
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv',skiprows=[1,2,3])
df

,Sno,State / Union Territory,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,4,West Bengal,91276115,62183113,29093002,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
1,5,Madhya Pradesh,72626809,52557404,20069405,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
2,6,Tamil Nadu,72147030,37229590,34917440,"130,058 km2 (50,216 sq mi)","555/km2 (1,440/sq mi)",996
3,7,Rajasthan,68548437,51500352,17048085,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
4,8,Karnataka,61095297,37469335,23625962,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),973
5,9,Gujarat,60439692,34694609,25745083,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
6,10,Andhra Pradesh,49577103,34966693,14610410,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993
7,11,Odisha,41974218,34970562,7003656,"155,707 km2 (60,119 sq mi)",269/km2 (700/sq mi),979
8,12,Telengana,35003674,21395009,13608665,"112,077 km2 (43,273 sq mi)",312/km2 (810/sq mi),988
9,13,Kerala,33406061,17471135,15934926,"38,863 km2 (15,005 sq mi)","859/km2 (2,220/sq mi)",1084
10,14,Jharkhand,32988134,25055073,7933061,"79,714 km2 (30,778 sq mi)","414/km2 (1,070/sq mi)",948
11,15,Assam,31205576,26807034,4398542,"78,438 km2 (30,285 sq mi)","397/km2 (1,030/sq mi)",954
12,16,Punjab,27743338,17344192,10399146,"50,362 km2 (19,445 sq mi)","550/km2 (1,400/sq mi)",895
13,17,Chhattisgarh,25545198,19607961,5937237,"135,191 km2 (52,198 sq mi)",189/km2 (490/sq mi),991
14,18,Haryana,25351462,16509359,8842103,"44,212 km2 (17,070 sq mi)","573/km2 (1,480/sq mi)",879
15,19,Uttarakhand,10086292,7036954,3049338,"53,483 km2 (20,650 sq mi)",189/km2 (490/sq mi),963
16,20,Himachal Pradesh,6864602,6176050,688552,"55,673 km2 (21,495 sq mi)",123/km2 (320/sq mi),972
17,21,Tripura,3673917,2712464,961453,"10,486 km2 (4,049 sq mi)",350/km2 (910/sq mi),960
18,22,Meghalaya,2966889,2371439,595450,"22,429 km2 (8,660 sq mi)",132/km2 (340/sq mi),989
19,23,Manipur,2570390,1793875,776515,"22,327 km2 (8,621 sq mi)",122/km2 (320/sq mi),992
20,24,Nagaland,1978502,1407536,570966,"16,579 km2 (6,401 sq mi)",119/km2 (310/sq mi),931
21,25,Goa,1458545,551731,906814,"3,702 km2 (1,429 sq mi)","394/km2 (1,020/sq mi)",973
22,26,Arunachal Pradesh,1383727,1066358,317369,"83,743 km2 (32,333 sq mi)",17/km2 (44/sq mi),938
23,27,Mizoram,1097206,525435,571771,"21,081 km2 (8,139 sq mi)",52/km2 (130/sq mi),976
24,28,Sikkim,610577,456999,153578,"7,096 km2 (2,740 sq mi)",86/km2 (220/sq mi),890
25,29,Delhi,16787941,419042,16368899,"1,484 km2 (573 sq mi)","11,297/km2 (29,260/sq mi)",868
26,30,Jammu and Kashmir,12267032,9064220,3202812,"125,535 km2 (48,469 sq mi)",98/km2 (250/sq mi),890
27,31,Puducherry,1247953,395200,852753,479 km2 (185 sq mi),"2,598/km2 (6,730/sq mi)",1037
28,32,Chandigarh,1055450,28991,1026459,114 km2 (44 sq mi),"9,252/km2 (23,960/sq mi)",818
29,33,Dadra and Nagar Haveli and Daman and Diu,585764,243510,342254,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
30,34,Andaman and Nicobar Islands,380581,237093,143488,"8,249 km2 (3,185 sq mi)",46/km2 (120/sq mi),876
31,35,Ladakh,274000,43840,230160,"96,701 km2 (37,336 sq mi)",2.8/km2 (7.3/sq mi),853
32,36,Lakshadweep,64473,14141,50332,32 km2 (12 sq mi),"2,013/km2 (5,210/sq mi)",946

In [11]:
#To change the index of column or making highlighting to that column.
#(4)index_col
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv',index_col='State / Union Territory')
df

,Sno,Population,Rural population,Urban population,Area,Density,Gender Ratio
State / Union Territory,,,,,,,
Uttar Pradesh,1,199812341,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
Maharashtra,2,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
Bihar,3,104099452,92341436,11758016,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
West Bengal,4,91276115,62183113,29093002,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
Madhya Pradesh,5,72626809,52557404,20069405,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
Tamil Nadu,6,72147030,37229590,34917440,"130,058 km2 (50,216 sq mi)","555/km2 (1,440/sq mi)",996
Rajasthan,7,68548437,51500352,17048085,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
Karnataka,8,61095297,37469335,23625962,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),973
Gujarat,9,60439692,34694609,25745083,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
Andhra Pradesh,10,49577103,34966693,14610410,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993
Odisha,11,41974218,34970562,7003656,"155,707 km2 (60,119 sq mi)",269/km2 (700/sq mi),979
Telengana,12,35003674,21395009,13608665,"112,077 km2 (43,273 sq mi)",312/km2 (810/sq mi),988
Kerala,13,33406061,17471135,15934926,"38,863 km2 (15,005 sq mi)","859/km2 (2,220/sq mi)",1084
Jharkhand,14,32988134,25055073,7933061,"79,714 km2 (30,778 sq mi)","414/km2 (1,070/sq mi)",948
Assam,15,31205576,26807034,4398542,"78,438 km2 (30,285 sq mi)","397/km2 (1,030/sq mi)",954
Punjab,16,27743338,17344192,10399146,"50,362 km2 (19,445 sq mi)","550/km2 (1,400/sq mi)",895
Chhattisgarh,17,25545198,19607961,5937237,"135,191 km2 (52,198 sq mi)",189/km2 (490/sq mi),991
Haryana,18,25351462,16509359,8842103,"44,212 km2 (17,070 sq mi)","573/km2 (1,480/sq mi)",879
Uttarakhand,19,10086292,7036954,3049338,"53,483 km2 (20,650 sq mi)",189/km2 (490/sq mi),963
Himachal Pradesh,20,6864602,6176050,688552,"55,673 km2 (21,495 sq mi)",123/km2 (320/sq mi),972
Tripura,21,3673917,2712464,961453,"10,486 km2 (4,049 sq mi)",350/km2 (910/sq mi),960
Meghalaya,22,2966889,2371439,595450,"22,429 km2 (8,660 sq mi)",132/km2 (340/sq mi),989
Manipur,23,2570390,1793875,776515,"22,327 km2 (8,621 sq mi)",122/km2 (320/sq mi),992
Nagaland,24,1978502,1407536,570966,"16,579 km2 (6,401 sq mi)",119/km2 (310/sq mi),931
Goa,25,1458545,551731,906814,"3,702 km2 (1,429 sq mi)","394/km2 (1,020/sq mi)",973
Arunachal Pradesh,26,1383727,1066358,317369,"83,743 km2 (32,333 sq mi)",17/km2 (44/sq mi),938
Mizoram,27,1097206,525435,571771,"21,081 km2 (8,139 sq mi)",52/km2 (130/sq mi),976
Sikkim,28,610577,456999,153578,"7,096 km2 (2,740 sq mi)",86/km2 (220/sq mi),890
Delhi,29,16787941,419042,16368899,"1,484 km2 (573 sq mi)","11,297/km2 (29,260/sq mi)",868
Jammu and Kashmir,30,12267032,9064220,3202812,"125,535 km2 (48,469 sq mi)",98/km2 (250/sq mi),890
Puducherry,31,1247953,395200,852753,479 km2 (185 sq mi),"2,598/km2 (6,730/sq mi)",1037
Chandigarh,32,1055450,28991,1026459,114 km2 (44 sq mi),"9,252/km2 (23,960/sq mi)",818
Dadra and Nagar Haveli and Daman and Diu,33,585764,243510,342254,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
Andaman and Nicobar Islands,34,380581,237093,143488,"8,249 km2 (3,185 sq mi)",46/km2 (120/sq mi),876
Ladakh,35,274000,43840,230160,"96,701 km2 (37,336 sq mi)",2.8/km2 (7.3/sq mi),853
Lakshadweep,36,64473,14141,50332,32 km2 (12 sq mi),"2,013/km2 (5,210/sq mi)",946

In [12]:
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv',index_col=2)
df

,Sno,State / Union Territory,Rural population,Urban population,Area,Density,Gender Ratio
Population,,,,,,,
199812341,1,Uttar Pradesh,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
112374333,2,Maharashtra,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
104099452,3,Bihar,92341436,11758016,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
91276115,4,West Bengal,62183113,29093002,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
72626809,5,Madhya Pradesh,52557404,20069405,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
72147030,6,Tamil Nadu,37229590,34917440,"130,058 km2 (50,216 sq mi)","555/km2 (1,440/sq mi)",996
68548437,7,Rajasthan,51500352,17048085,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
61095297,8,Karnataka,37469335,23625962,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),973
60439692,9,Gujarat,34694609,25745083,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
49577103,10,Andhra Pradesh,34966693,14610410,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993
41974218,11,Odisha,34970562,7003656,"155,707 km2 (60,119 sq mi)",269/km2 (700/sq mi),979
35003674,12,Telengana,21395009,13608665,"112,077 km2 (43,273 sq mi)",312/km2 (810/sq mi),988
33406061,13,Kerala,17471135,15934926,"38,863 km2 (15,005 sq mi)","859/km2 (2,220/sq mi)",1084
32988134,14,Jharkhand,25055073,7933061,"79,714 km2 (30,778 sq mi)","414/km2 (1,070/sq mi)",948
31205576,15,Assam,26807034,4398542,"78,438 km2 (30,285 sq mi)","397/km2 (1,030/sq mi)",954
27743338,16,Punjab,17344192,10399146,"50,362 km2 (19,445 sq mi)","550/km2 (1,400/sq mi)",895
25545198,17,Chhattisgarh,19607961,5937237,"135,191 km2 (52,198 sq mi)",189/km2 (490/sq mi),991
25351462,18,Haryana,16509359,8842103,"44,212 km2 (17,070 sq mi)","573/km2 (1,480/sq mi)",879
10086292,19,Uttarakhand,7036954,3049338,"53,483 km2 (20,650 sq mi)",189/km2 (490/sq mi),963
6864602,20,Himachal Pradesh,6176050,688552,"55,673 km2 (21,495 sq mi)",123/km2 (320/sq mi),972
3673917,21,Tripura,2712464,961453,"10,486 km2 (4,049 sq mi)",350/km2 (910/sq mi),960
2966889,22,Meghalaya,2371439,595450,"22,429 km2 (8,660 sq mi)",132/km2 (340/sq mi),989
2570390,23,Manipur,1793875,776515,"22,327 km2 (8,621 sq mi)",122/km2 (320/sq mi),992
1978502,24,Nagaland,1407536,570966,"16,579 km2 (6,401 sq mi)",119/km2 (310/sq mi),931
1458545,25,Goa,551731,906814,"3,702 km2 (1,429 sq mi)","394/km2 (1,020/sq mi)",973
1383727,26,Arunachal Pradesh,1066358,317369,"83,743 km2 (32,333 sq mi)",17/km2 (44/sq mi),938
1097206,27,Mizoram,525435,571771,"21,081 km2 (8,139 sq mi)",52/km2 (130/sq mi),976
610577,28,Sikkim,456999,153578,"7,096 km2 (2,740 sq mi)",86/km2 (220/sq mi),890
16787941,29,Delhi,419042,16368899,"1,484 km2 (573 sq mi)","11,297/km2 (29,260/sq mi)",868
12267032,30,Jammu and Kashmir,9064220,3202812,"125,535 km2 (48,469 sq mi)",98/km2 (250/sq mi),890
1247953,31,Puducherry,395200,852753,479 km2 (185 sq mi),"2,598/km2 (6,730/sq mi)",1037
1055450,32,Chandigarh,28991,1026459,114 km2 (44 sq mi),"9,252/km2 (23,960/sq mi)",818
585764,33,Dadra and Nagar Haveli and Daman and Diu,243510,342254,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
380581,34,Andaman and Nicobar Islands,237093,143488,"8,249 km2 (3,185 sq mi)",46/km2 (120/sq mi),876
274000,35,Ladakh,43840,230160,"96,701 km2 (37,336 sq mi)",2.8/km2 (7.3/sq mi),853
64473,36,Lakshadweep,14141,50332,32 km2 (12 sq mi),"2,013/km2 (5,210/sq mi)",946

In [13]:
#(5)Header:
df = pd.read_csv('E:\\PYTHON\\population_india_census2011.csv',header=2)
df

,2,Maharashtra,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
0,3,Bihar,104099452,92341436,11758016,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
1,4,West Bengal,91276115,62183113,29093002,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
2,5,Madhya Pradesh,72626809,52557404,20069405,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
3,6,Tamil Nadu,72147030,37229590,34917440,"130,058 km2 (50,216 sq mi)","555/km2 (1,440/sq mi)",996
4,7,Rajasthan,68548437,51500352,17048085,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
5,8,Karnataka,61095297,37469335,23625962,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),973
6,9,Gujarat,60439692,34694609,25745083,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
7,10,Andhra Pradesh,49577103,34966693,14610410,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993
8,11,Odisha,41974218,34970562,7003656,"155,707 km2 (60,119 sq mi)",269/km2 (700/sq mi),979
9,12,Telengana,35003674,21395009,13608665,"112,077 km2 (43,273 sq mi)",312/km2 (810/sq mi),988
10,13,Kerala,33406061,17471135,15934926,"38,863 km2 (15,005 sq mi)","859/km2 (2,220/sq mi)",1084
11,14,Jharkhand,32988134,25055073,7933061,"79,714 km2 (30,778 sq mi)","414/km2 (1,070/sq mi)",948
12,15,Assam,31205576,26807034,4398542,"78,438 km2 (30,285 sq mi)","397/km2 (1,030/sq mi)",954
13,16,Punjab,27743338,17344192,10399146,"50,362 km2 (19,445 sq mi)","550/km2 (1,400/sq mi)",895
14,17,Chhattisgarh,25545198,19607961,5937237,"135,191 km2 (52,198 sq mi)",189/km2 (490/sq mi),991
15,18,Haryana,25351462,16509359,8842103,"44,212 km2 (17,070 sq mi)","573/km2 (1,480/sq mi)",879
16,19,Uttarakhand,10086292,7036954,3049338,"53,483 km2 (20,650 sq mi)",189/km2 (490/sq mi),963
17,20,Himachal Pradesh,6864602,6176050,688552,"55,673 km2 (21,495 sq mi)",123/km2 (320/sq mi),972
18,21,Tripura,3673917,2712464,961453,"10,486 km2 (4,049 sq mi)",350/km2 (910/sq mi),960
19,22,Meghalaya,2966889,2371439,595450,"22,429 km2 (8,660 sq mi)",132/km2 (340/sq mi),989
20,23,Manipur,2570390,1793875,776515,"22,327 km2 (8,621 sq mi)",122/km2 (320/sq mi),992
21,24,Nagaland,1978502,1407536,570966,"16,579 km2 (6,401 sq mi)",119/km2 (310/sq mi),931
22,25,Goa,1458545,551731,906814,"3,702 km2 (1,429 sq mi)","394/km2 (1,020/sq mi)",973
23,26,Arunachal Pradesh,1383727,1066358,317369,"83,743 km2 (32,333 sq mi)",17/km2 (44/sq mi),938
24,27,Mizoram,1097206,525435,571771,"21,081 km2 (8,139 sq mi)",52/km2 (130/sq mi),976
25,28,Sikkim,610577,456999,153578,"7,096 km2 (2,740 sq mi)",86/km2 (220/sq mi),890
26,29,Delhi,16787941,419042,16368899,"1,484 km2 (573 sq mi)","11,297/km2 (29,260/sq mi)",868
27,30,Jammu and Kashmir,12267032,9064220,3202812,"125,535 km2 (48,469 sq mi)",98/km2 (250/sq mi),890
28,31,Puducherry,1247953,395200,852753,479 km2 (185 sq mi),"2,598/km2 (6,730/sq mi)",1037
29,32,Chandigarh,1055450,28991,1026459,114 km2 (44 sq mi),"9,252/km2 (23,960/sq mi)",818
30,33,Dadra and Nagar Haveli and Daman and Diu,585764,243510,342254,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
31,34,Andaman and Nicobar Islands,380581,237093,143488,"8,249 km2 (3,185 sq mi)",46/km2 (120/sq mi),876
32,35,Ladakh,274000,43840,230160,"96,701 km2 (37,336 sq mi)",2.8/km2 (7.3/sq mi),853
33,36,Lakshadweep,64473,14141,50332,32 km2 (12 sq mi),"2,013/km2 (5,210/sq mi)",946